/**
 * СГЕНЕРИРОВАНО scripts/gen-tagsru.ts — руками не править: следующий прогон
 * перезапишет. Кривой перевод Steam чинится в lib/tagsru.overrides.ts, а
 * читается всё через tagRu из lib/tagsru.ts.
 *
 * Источник: populartags Steam. Пар: 429.
 */
export const TAGS_RU_STEAM: Readonly<Record<string, string>> = {
  '1980s': '80-е',
  "1990's": '90-е',
  '2.5D': '2.5D',
  '2D': '2D',
  '2D Fighter': '2D-файтинг',
  '2D Platformer': '2D-платформер',
  '360 Video': 'Панорамное видео',
  '3D': '3D',
  '3D Fighter': '3D-файтинг',
  '3D Platformer': '3D-платформер',
  '4 Player Local': 'Локальная игра на четверых',
  '4X': '4X',
  '6DOF': 'Свобода движения',
  '8-bit Music': '8-битная музыка',
  'ATV': 'Квадроциклы',
  'Abstract': 'Абстрактная',
  'Action': 'Экшен',
  'Action RPG': 'Ролевой экшен',
  'Action RTS': 'Экшен-RTS',
  'Action Roguelike': 'Экшен-рогалик',
  'Action-Adventure': 'Приключенческий экшен',
  'Addictive': 'Затягивающая',
  'Adventure': 'Приключение',
  'Agriculture': 'Сельское хозяйство',
  'Aliens': 'Инопланетяне',
  'Alternate History': 'Альтернативная история',
  'Animals': 'Животные',
  'Animation & Modeling': 'Анимация и моделирование',
  'Anime': 'Аниме',
  'Arcade': 'Аркада',
  'Archery': 'Стрельба из лука',
  'Arena Shooter': 'Арена-шутер',
  'Artificial Intelligence': 'Искусственный интеллект',
  'Assassins': 'Ассассины',
  'Asymmetric VR': 'Асимметричная VR',
  'Asynchronous Multiplayer': 'Асинхронный мультиплеер',
  'Atmospheric': 'Атмосферная',
  'Audio Production': 'Работа со звуком',
  'Auto Battler': 'Автобаттлер',
  'Automation': 'Автоматизация',
  'Automobile Sim': 'Автосимулятор',
  'BMX': 'Веломотокросс',
  'Base Building': 'Строительство базы',
  'Baseball': 'Бейсбол',
  'Based On A Novel': 'По мотивам книги',
  'Basketball': 'Баскетбол',
  'Battle Royale': 'Королевская битва',
  "Beat 'em up": "Beat 'em up",
  'Beautiful': 'Красивая',
  'Benchmark': 'Бенчмарк',
  'Bikes': 'Байки',
  'Billiards': 'Бильярд',
  'Birds': 'Птицы',
  'Board Game': 'Настольная с полем',
  'Boomer Shooter': 'Бумерский шутер',
  'Boss Rush': 'Boss Rush',
  'Bowling': 'Боулинг',
  'Boxing': 'Бокс',
  'Building': 'Строительство',
  'Bullet Heaven': 'Пулевой рай',
  'Bullet Hell': 'Пулевой ад',
  'Bullet Time': 'Замедление времени',
  'CRPG': 'Компьютерная ролевая игра',
  'Capitalism': 'Капитализм',
  'Capybaras': 'Капибары',
  'Card Battler': 'Карточный баттлер',
  'Card Game': 'Карточная игра',
  'Cartoon': 'Мультфильмы',
  'Cartoony': 'Мультипликация',
  'Casual': 'Казуальная игра',
  'Cats': 'Котики',
  'Character Action Game': 'Яркий главный герой',
  'Character Customization': 'Кастомизация персонажа',
  'Chess': 'Шахматы',
  'Choices Matter': 'Решения с последствиями',
  'Choose Your Own Adventure': 'Выбери себе приключение',
  'Cinematic': 'Кинематографичная',
  'City Builder': 'Градостроение',
  'Class-Based': 'Разделение на классы',
  'Classic': 'Классика',
  'Cleaning': 'Уборка',
  'Co-op': 'Кооператив',
  'Co-op Campaign': 'Совместная кампания',
  'Cold War': 'Холодная война',
  'Collectathon': 'Коллектатон',
  'Colony Sim': 'Симулятор колонии',
  'Colorful': 'Цветастая',
  'Combat': 'Бой',
  'Combat Racing': 'Боевые гонки',
  'Comedy': 'Юмор',
  'Comic Book': 'По комиксу',
  'Competitive': 'Соревновательная',
  'Conspiracy': 'Заговор',
  'Controller': 'Контроллер',
  'Cooking': 'Кулинария',
  'Cozy': 'Уютная',
  'Crafting': 'Крафтинг',
  'Creature Collector': 'Коллекционирование существ',
  'Cricket': 'Крикет',
  'Crime': 'Криминал',
  'Cult': 'Культ',
  'Cute': 'Милая',
  'Cyberpunk': 'Киберпанк',
  'Cycling': 'Велосипеды',
  'Dark': 'Мрачная',
  'Dark Comedy': 'Чёрная комедия',
  'Dark Fantasy': 'Тёмное фэнтези',
  'Dark Humor': 'Чёрный юмор',
  'Dating Sim': 'Симулятор свиданий',
  'Deckbuilding': 'Построение колоды',
  'Decorating': 'Декорирование',
  'Demons': 'Демоны',
  'Design & Illustration': 'Дизайн и иллюстрация',
  'Desktop Companion': 'Настольный компаньон',
  'Destruction': 'Разрушения',
  'Detective': 'Детектив',
  'Dialogue Heavy': 'Беседы',
  'Dice': 'Игральные кости',
  'Difficult': 'Сложная',
  'Dinosaurs': 'Динозавры',
  'Diplomacy': 'Дипломатия',
  'Dogs': 'Собаки',
  'Dragons': 'Драконы',
  'Driving': 'Вождение',
  'Dungeon Crawler': 'Подземелья',
  'Dwarves': 'Дворфы',
  'Dynamic Narration': 'Динамическое повествование',
  'Dystopian': 'Антиутопия',
  'Early Access': 'Ранний доступ',
  'Economy': 'Экономика',
  'Education': 'Образование',
  'Electronic Music': 'Электронная музыка',
  'Elves': 'Эльфы',
  'Emotional': 'Эмоциональная',
  'Epic': 'Эпичная',
  'Episodic': 'Сериал',
  'Escape Room': 'Квест-комната',
  'Espionage': 'Шпионаж',
  'Experimental': 'Экспериментальная',
  'Exploration': 'Исследования',
  'Extraction Shooter': 'Шутер с эвакуацией',
  'FMV': 'FMV-игра',
  'FPS': 'Шутер от первого лица',
  'Faith': 'Верования',
  'Falling Blocks': 'Падающие блоки',
  'Family Friendly': 'Для всей семьи',
  'Fantasy': 'Фэнтези',
  'Farming': 'Фермерство',
  'Farming Sim': 'Симулятор фермы',
  'Fast-Paced': 'Быстрая',
  'Female Protagonist': 'Протагонистка',
  'Fighting': 'Файтинг',
  'First-Person': 'От первого лица',
  'Fishing': 'Рыбалка',
  'Flight': 'Полёты',
  'Football (American)': 'Американский футбол',
  'Football (Soccer)': 'Футбол',
  'Foxes': 'Лисицы',
  'Free to Play': 'Бесплатная игра',
  'Funny': 'Смешная',
  'Futuristic': 'Будущее',
  'Gambling': 'Азартная',
  'Game Development': 'Разработка игр',
  'Gaming': 'Об играх',
  'God Game': 'Симулятор бога',
  'Golf': 'Гольф',
  'Gore': 'Кровь',
  'Gothic': 'Готика',
  'Grand Strategy': 'Глобальная стратегия',
  'Great Soundtrack': 'Отличный саундтрек',
  'Grid-Based Movement': 'Перемещение по сетке',
  'Gun Customization': 'Кастомизация оружия',
  'Hack and Slash': 'Слэшер',
  'Hacking': 'Хакерство',
  'Hand-drawn': 'Рисованная графика',
  'Hardware': 'Устройства',
  'Heist': 'Ограбления',
  'Hentai': 'Хентай',
  'Hero Shooter': 'Геройский шутер',
  'Hex Grid': 'Шестиугольная карта',
  'Hidden Object': 'Поиск предметов',
  'Historical': 'Историческая',
  'Hobby Sim': 'Симулятор хобби',
  'Hockey': 'Хоккей',
  'Horror': 'Хоррор',
  'Horses': 'Лошади',
  'Hunting': 'Охота',
  'Idler': 'Idle-игра',
  'Immersive': 'Иммерсивная игра',
  'Immersive Sim': 'Иммерсивный симулятор',
  'Incremental': 'Инкрементальная',
  'Indie': 'Инди',
  'Instrumental Music': 'Инструментальная музыка',
  'Intentionally Awkward Controls': 'Нарочито неудобное управление',
  'Interactive Fiction': 'Интерактивная литература',
  'Inventory Management': 'Менеджмент инвентаря',
  'Investigation': 'Расследования',
  'Isometric': 'Изометрия',
  'JRPG': 'Японская ролевая игра',
  'Job Simulator': 'Симулятор работы',
  'Jump Scare': 'Скример',
  'LGBTQ+': 'ЛГБТК+',
  'Language Learning': 'Изучение языков',
  'Lemmings': 'Лемминги',
  'Level Editor': 'Редактор уровней',
  'Life Sim': 'Симулятор жизни',
  'Linear': 'Линейная',
  'Local Co-Op': 'Локальный кооператив',
  'Local Multiplayer': 'Локальный мультиплеер',
  'Logic': 'Логика',
  'Loot': 'Лут',
  'Looter Shooter': 'Лутер-шутер',
  'Lore-Rich': 'Проработанная вселенная',
  'Lovecraftian': 'Лавкрафт',
  'MMORPG': 'MMORPG',
  'MOBA': 'MOBA',
  'Magic': 'Магия',
  'Mahjong': 'Маджонг',
  'Management': 'Менеджмент',
  'Mars': 'Марс',
  'Martial Arts': 'Боевые искусства',
  'Massively Multiplayer': 'ММО',
  'Match 3': 'Три в ряд',
  'Mechs': 'Мехи',
  'Medical Sim': 'Медицинский симулятор',
  'Medieval': 'Средневековье',
  'Memes': 'Мемы',
  'Metroidvania': 'Метроидвания',
  'Military': 'Военные действия',
  'Mini Golf': 'Мини-гольф',
  'Minigames': 'Мини-игры',
  'Minimalist': 'Минимализм',
  'Mining': 'Горное дело',
  'Mod': 'Модификации',
  'Moddable': 'Поддержка модификаций',
  'Modern': 'Современность',
  'Motocross': 'Мотокросс',
  'Motorbike': 'Мотоциклы',
  'Mouse Only': 'Управление мышью',
  'Multiplayer': 'Для нескольких игроков',
  'Multiple Endings': 'Несколько концовок',
  'Music': 'Музыка',
  'Music-Based Procedural Generation': 'Генерация на основе музыки',
  'Musou': 'Мусоу',
  'Mystery': 'Тайна',
  'Mystery Dungeon': 'Загадочные подземелья',
  'Mythology': 'Мифология',
  'Narrative': 'Повествование',
  'Nature': 'Природа',
  'Naval': 'Флот',
  'Naval Combat': 'Морской бой',
  'Ninja': 'Ниндзя',
  'Noir': 'Нуар',
  'Nonlinear': 'Нелинейная',
  'Nostalgia': 'Ностальгия',
  'Nudity': 'Нагота',
  'Offroad': 'Бездорожье',
  'Old School': 'Олдскул',
  'On-Rails Shooter': 'Рельсовый шутер',
  'Online Co-Op': 'Сетевой кооператив',
  'Open World': 'Открытый мир',
  'Open World Survival Craft': 'Симулятор выживания и крафтинга в открытом мире',
  'Organizing': 'Организация',
  'Otome': 'Отомэ',
  'Outbreak Sim': 'Симулятор эпидемии',
  'Parkour': 'Паркур',
  'Parody': 'Пародия',
  'Party': 'Вечеринка',
  'Party Game': 'Командная игра',
  'Party-Based RPG': 'Партийная ролевая игра',
  'Perma Death': 'Одна жизнь',
  'Philosophical': 'Философская',
  'Photo Editing': 'Обработка фото',
  'Physics': 'Физика',
  'Pinball': 'Пинбол',
  'Pirates': 'Пираты',
  'Pixel Graphics': 'Пиксельная графика',
  'Platformer': 'Платформер',
  'Point & Click': 'Point & Click',
  'Poker': 'Покер',
  'Political Sim': 'Политический симулятор',
  'Post-apocalyptic': 'Постапокалипсис',
  'Precision Platformer': 'Платформер на точность',
  'Procedural Generation': 'Процедурная генерация',
  'Programming': 'Программирование',
  'Psychedelic': 'Психоделия',
  'Psychological': 'Психологическая',
  'Psychological Horror': 'Психологический хоррор',
  'Puzzle': 'Головоломка',
  'Puzzle Platformer': 'Головоломка-платформер',
  'PvE': 'Игрок против ИИ',
  'PvP': 'Игрок против игрока',
  'Quick-Time Events': 'QTE',
  'RPG': 'Ролевая игра',
  'RTS': 'Стратегия в реальном времени',
  'Racing': 'Гонки',
  'Real Time Tactics': 'Тактика в реальном времени',
  'Real-Time': 'В реальном времени',
  'Real-Time with Pause': 'Можно приостановить',
  'Realistic': 'Реализм',
  'Reboot': 'Перезапуск',
  'Relaxing': 'Расслабляющая',
  'Remake': 'Ремейк',
  'Replay Value': 'Реиграбельность',
  'Resource Management': 'Управление ресурсами',
  'Retro': 'Ретро',
  'Rhythm': 'Ритм-игра',
  'Robots': 'Роботы',
  'Rock Music': 'Рок-музыка',
  'Roguelike': 'Рогалик',
  'Roguelike Deckbuilder': 'Карточный рогалик',
  'Roguelite': 'Упрощённый рогалик',
  'Romance': 'Романтика',
  'Rome': 'Рим',
  'Rugby': 'Регби',
  'Runner': 'Раннер',
  'Sailing': 'Мореплавание',
  'Samurai': 'Самураи',
  'Sandbox': 'Песочница',
  'Satire': 'Сатира',
  'Sci-fi': 'Научная фантастика',
  'Science': 'Наука',
  'Score Attack': 'Набор очков',
  'Sequel': 'Сиквел',
  'Sexual Content': 'Сексуальный контент',
  "Shoot 'Em Up": "Shoot 'em up",
  'Shooter': 'Шутер',
  'Shop Keeper': 'Работа в магазине',
  'Short': 'Короткая',
  'Side Scroller': 'Вид сбоку',
  'Silent Protagonist': 'Молчаливый главный герой',
  'Simulation': 'Симулятор',
  'Singleplayer': 'Для одного игрока',
  'Skateboarding': 'Скейтбординг',
  'Skating': 'Катание',
  'Skiing': 'Лыжи',
  'Sniper': 'Снайперство',
  'Snow': 'Снег',
  'Snowboarding': 'Сноубординг',
  'Social Deduction': 'Социальная дедукция',
  'Software': 'Программное обеспечение',
  'Software Training': 'Обучение работе с ПО',
  'Sokoban': 'Сокобан',
  'Solitaire': 'Пасьянс',
  'Souls-like': 'Похожа на Dark Souls',
  'Soundtrack': 'Саундтрек',
  'Space': 'Космос',
  'Space Sim': 'Космический симулятор',
  'Spaceships': 'Космические корабли',
  'Spectacle fighter': 'Зрелищные сражения',
  'Spelling': 'Правописание',
  'Split Screen': 'Разделение экрана',
  'Sports': 'Спорт',
  'Stealth': 'Стелс',
  'Steampunk': 'Стимпанк',
  'Story Rich': 'Глубокий сюжет',
  'Strategy': 'Стратегия',
  'Strategy RPG': 'Ролевая стратегия',
  'Stylized': 'Стилизация',
  'Submarine': 'Подводная лодка',
  'Superhero': 'Супергерои',
  'Supernatural': 'Сверхъестественное',
  'Surreal': 'Сюрреалистичная',
  'Survival': 'Выживание',
  'Survival Horror': 'Хоррор на выживание',
  'Swordplay': 'Сражения на мечах',
  'Tabletop': 'Настольная игра',
  'Tactical': 'Тактика',
  'Tactical RPG': 'Тактическая ролевая игра',
  'Tanks': 'Танки',
  'Team-Based': 'Командная',
  'Tennis': 'Теннис',
  'Text-Based': 'Текстовая',
  'Third Person': 'От третьего лица',
  'Third-Person Shooter': 'Шутер от третьего лица',
  'Thriller': 'Триллер',
  'Time Attack': 'Игра на время',
  'Time Management': 'Тайм-менеджмент',
  'Time Manipulation': 'Контроль времени',
  'Time Travel': 'Путешествия во времени',
  'Top-Down': 'Вид сверху',
  'Top-Down Shooter': 'Шутер с видом сверху',
  'Touch-Friendly': 'Сенсорное управление',
  'Tower Defense': 'Башенная защита',
  'TrackIR': 'TrackIR',
  'Trading': 'Торговля',
  'Trading Card Game': 'Коллекционная карточная игра',
  'Traditional Roguelike': 'Традиционный рогалик',
  'Trains': 'Поезда',
  'Transhumanism': 'Трансгуманизм',
  'Transportation': 'Транспорт',
  'Trivia': 'Викторина',
  'Turn-Based': 'Пошаговая',
  'Turn-Based Combat': 'Пошаговые сражения',
  'Turn-Based Strategy': 'Пошаговая стратегия',
  'Turn-Based Tactics': 'Пошаговая тактика',
  'Tutorial': 'Обучение',
  'Twin Stick Shooter': 'Твин-стик шутер',
  'Typing': 'Печатание',
  'Underground': 'Подземная',
  'Underwater': 'Подводный мир',
  'Utilities': 'Утилиты',
  'VR': 'VR',
  'Vampires': 'Вампиры',
  'Vehicular Combat': 'Гонки на выживание',
  'Video Production': 'Видеопродакшн',
  'Vikings': 'Викинги',
  'Villain Protagonist': 'Злодей-протагонист',
  'Violent': 'Насилие',
  'Visual Novel': 'Визуальная новелла',
  'Voice Control': 'Управление голосом',
  'Volleyball': 'Волейбол',
  'Voxel': 'Воксельная графика',
  'Walking Simulator': 'Симулятор ходьбы',
  'War': 'Война',
  'Wargame': 'Военные конфликты',
  'Werewolves': 'Оборотни',
  'Western': 'Вестерн',
  'Wholesome': 'Душевная',
  'Wolves': 'Волки',
  'Word Game': 'Словесная',
  'World War I': 'Первая мировая война',
  'World War II': 'Вторая мировая война',
  'Wrestling': 'Реслинг',
  'Wuxia': 'Уся',
  'Xianxia': 'Сянься',
  'Zombies': 'Зомби',
  'Zoo': 'Зоопарк',
  'eSports': 'Киберспорт',
}
